version : '2'

services:
        
    proftpd:
        build: .
        ports:
            - "2200:22"
            - "21:21"
            - "2000:20"
            - "8000:80"
        volumes:
            - ftpdata:/var/proftpd/home
            - ./ssl/:/etc/ssl/
        environment:
            - SETUP_REFRESH_FREQUENCY=3600
volumes:
    ftpdata:
    