version : '2'

services:
        
    admin:
        build: 
            context: .
            dockerfile: Dockerfile-admin
        volumes:
            - ftpdata:/var/proftpd/
            - ./conf.json:/etc/proftpd/conf.json
            
    proftpd_ftps:
        depends_on:
            - admin
        build: 
            context: .
            dockerfile: Dockerfile-proftpd-alpine-source
        ports:
            - "21:21"
            - "30000-30099:30000-30099" # passive ports
        volumes:
            - ftpdata:/var/proftpd/
            - ./ssl/:/etc/ssl/
        environment:
            - SETUP_REFRESH_FREQUENCY=3600
            - PROFTPD_CONF_FILE=/etc/proftpd/proftpd_ftps.conf
            
    proftpd_sftp:
        depends_on:
            - admin
        build: 
            context: .
            dockerfile: Dockerfile-proftpd-alpine-source
        ports:
            - "2200:22"
        volumes:
            - ftpdata:/var/proftpd/
            - ./ssl/:/etc/ssl/
        environment:
            - PROFTPD_CONF_FILE=/etc/proftpd/proftpd_sftp.conf
            
volumes:
    ftpdata:
    