version : '2'

services:
        
    admin:
        build: 
            context: .
            dockerfile: Dockerfile-admin
        volumes:
            - ftpusers:/var/ftpusers/
            - rsakeys:/etc/pure-ftpd/authorized_keys
            - ./conf.json:/etc/proftpd/conf.json
        environment:
            - FTP_USERS_FILE=/var/ftpusers/pureftp.passwd
            - SFTP_USERS_FILE=/var/ftpusers/sftpusers
            - FTP_HOME_PATH=/home/ftpusers
            - USER_KEYS_PATH=
                        
    ftps:
        image: stilliard/pure-ftpd:hardened
        links:
            - admin 
        ports:
            - "21:21"
            - "30000-30099:30000-30099"
      
        volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
            - ftphomes:/home/ftpusers
            - ftpusers:/etc/pure-ftpd/passwd
            - rsakeys:/etc/pure-ftpd/authorized_keys
      
        #depends_on:
        #    - admin
        environment:
            - FTP_PASSIVE_PORTS=30000:30099
            - FTP_MAX_CLIENTS=50
            - FTP_MAX_CONNECTIONS=50
            - PURE_PASSWDFILE=/etc/pure-ftpd/passwd/pureftp.passwd
            
            
volumes:
    ftphomes:
    ftpusers:
    rsakeys:
    